### ISSUE TITLE
Support modules with replacements

### ISSUE THREAD

**Issue by andremarianiello** [nomad-software/vend#1]
during copying, the original module path is used for the module source. if the module should be replaced via a replace statement in go.mod, then the replacing module path should be used.

**Comment by nomad-software** [comment]
I thought long and hard about this and I left it out intentionally. Replace statements can come from anywhere and are likely only temporary replacements. The use cases for replace statements tend to be for development or for debugging not really candidates for long-term archiving of dependencies.

**Comment by andremarianiello** [comment]
Since this is intentional and not a bug, it might be a good idea to document it as this is unintuitive behavior (in my opinion).

**Comment by nomad-software** [comment]
It's not unintuitive behavior because it throws up too many questions. The intuitive thing to do is not to do it unless those questions can be answered in a sane way that is good for the majority of users.

**Comment by nomad-software** [comment]
I've updated the readme.

**Comment by andremarianiello** [comment]
Thanks!

**Comment by tadaskay** [comment]
@andremarianiello In case you still need it, I hacked in a very simple way to do the replace via flags: https://github.com/mysteriumnetwork/vend/commit/32923087c8e7d91815965c39c01b6480e614abd2 
Not very sophisticated, but works for our case.

**Comment by nomad-software** [comment]
Replacements are now supported.
