### ISSUE TITLE
Create a Website for this Repo

### ISSUE THREAD

**Issue by jfullstackdev** [nomad-software/vend#12]
Hi there. 

Is there a website for this repo? 

Because if you don't have, well, this repo can simply be turned into a website right away. Others will discover this project in that website.

Steps:
1. Go to Settings and look for `GitHub Pages`, scroll down. That's almost at the bottom.

2. You will see there: `Branch:none`, so you should change that to `master` because you have a `README.md` file in the master repo. This will be your page. Click `Save` first.

3. Then click `Choose a theme`, you select a predefined theme of your site.

4. Visit your site now! The URL will be `https://nomad-software.github.io/vend`. 

If you were amazed by that, simply read the documentation about GitHub Pages.

**Comment by nomad-software** [comment]
Hi, thanks for the advice but I don't think this small and simple tool requires a website.

**Comment by jfullstackdev** [comment]
@nomad-software , if I am not mistaken you authored one book dedicated for beginners learning PureBasic, right? Nice meeting you here! I learned a lot from your book way back 2017! Thanks a lot!

**Comment by jfullstackdev** [comment]
> Hi, thanks for the advice but I don't think this small and simple tool requires a website.

Maybe you just want to try `GitHub Pages`, it was actually created by GitHub so that you can turn your repo into a full-pledge website right away.

**Comment by nomad-software** [comment]
> @nomad-software , if I am not mistaken you authored one book dedicated for beginners learning PureBasic, right? Nice meeting you here! I learned a lot from your book way back 2017! Thanks a lot!

Yeah I used PureBasic quite a lot years ago. I think a lot of language designers today could learn a lot from its libraries as it was capable of pretty much anything out of the box. The book is on here too: https://github.com/nomad-software/purebasic-a-beginners-guide

**Comment by jfullstackdev** [comment]
Okay, thanks a lot.
