### ISSUE TITLE
How to download only one package? Why vend is not downloading .a files from repo?

### ISSUE THREAD

**Issue by punithck** [nomad-software/vend#14]
Hey 
I got 1 issue and 1 doubt here.
1)Is vend accepts any arguments? I just want to download one package fully in vendor.
2)My golang code is using module https://github.com/confluentinc/confluent-kafka-go. Here they static library at the path /kafka/librdkafka_vendor i.e librdkafka_darwin.a librdkafka_glibc_linux.a librdkafka_musl_linux.a librdkafka_windows.a
I couldnt see these files after doing the vend

**Comment by nomad-software** [comment]
Works perfectly for me
```
/media/Data/Projects/Go/src/github.com/nomad-software/test/vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor tree
.
├── bundle-import.sh
├── import.sh
├── librdkafka_darwin.a
├── librdkafka_glibc_linux.a
├── librdkafka.go
├── librdkafka_musl_linux.a
├── librdkafka_windows.a
├── LICENSES.txt
├── rdkafka.h
└── README.md

0 directories, 10 files
```
