### ISSUE TITLE
Copies Go files that the running Go version can't parse.

### ISSUE THREAD

**Issue by gannett-ggreer** [nomad-software/vend#15]
If a vendored module has `//go:build go1.18` lines while running go1.17 then running `gofmt -l .` (as a CI formatting check, for example) errors out because go1.17 doesn't understand go1.18 generics syntax.   Seems like `go vet` and `go build` are smart enough to avoid those files, however.  Can work around this with a more complex `gofmt` line that avoids `vendor` directory, like `find . \( -path ./vendor -prune \) -o -type f -name \*.go -print0 | xargs -0 gofmt -l`, so not sure exactly how urgent this is, but a parameter to avoid them would help.

Example Go file:
```
package main

import (
	"fmt"

	"golang.org/x/tools/godoc/util"
)

func main() {
	fmt.Println(util.IsText([]byte("foo")))
}
```

`go mod vendor`:
```
$ rm -rf vendor; go mod vendor; gofmt -l .; echo $?
0
```

`vend`:
```
$ rm -rf vendor; go run --mod=mod github.com/nomad-software/vend > /dev/null; gofmt -l . 2>&1 | grep : | tail
go: finding module for package github.com/nomad-software/vend
vendor/golang.org/x/tools/internal/lsp/testdata/keywords/empty_select.go:7:1: expected declaration, found '}'
vendor/golang.org/x/tools/internal/lsp/testdata/keywords/empty_switch.go:9:3: expected '}', found d
vendor/golang.org/x/tools/internal/lsp/testdata/keywords/empty_switch.go:11:1: expected declaration, found '}'
vendor/golang.org/x/tools/internal/lsp/testdata/keywords/keywords.go:71:1: expected operand, found '}'
vendor/golang.org/x/tools/internal/lsp/testdata/keywords/keywords.go:100:52: expected ';', found 'EOF'
vendor/golang.org/x/tools/internal/lsp/testdata/snippets/literal.go:21:2: expected operand, found '}'
vendor/golang.org/x/tools/internal/lsp/testdata/snippets/literal.go:22:2: missing ',' in composite literal
vendor/golang.org/x/tools/internal/lsp/testdata/statements/if_err_check_return.go:22:2: expected boolean expression, found assignment (missing parentheses around composite literal?)
vendor/golang.org/x/tools/internal/lsp/testdata/statements/if_err_check_return.go:26:2: expected operand, found 'if'
vendor/golang.org/x/tools/internal/lsp/testdata/statements/if_err_check_return.go:27:3: expected '}', found 'EOF'
```

**Comment by nomad-software** [comment]
It's a well known problem and not one, i think, `vend` shouldn't really fix.

* https://groups.google.com/g/golang-nuts/c/gyBNyJkHOIE
* https://github.com/golang/go/issues/22173
* https://github.com/golang/go/issues/33962

The whole point of `vend` is to copy everything. The solution is not to format the vendor folder.
A shorter command from the last link:

```
gofmt -l (find . -type f -name '*.go' | grep -v "/vendor/")
```
