### ISSUE TITLE
vend -package seems vendor extra dependencies

### ISSUE THREAD

**Issue by dfang** [nomad-software/vend#4]
how to reproduce ?

1. clone github.com/qor/qor-example, 
2. go mod init
3. vend -package github.com/qor/admin

in my case, it copies 

```
~/src/qor-demo λ  tree -L 1 vendor/
vendor/
├── github.com
├── go.uber.org
├── golang.org
└── modules.txt
```

at least qor/admin has no denpendency on zap or golang/x

**Comment by nomad-software** [comment]
That's not a valid `vend` command. This program only vendors dependencies for the current project at either package level or module level.

1. git clone github.com/qor/qor-example
2. cd github.com/qor/qor-example
3. vend [-package]
