### ISSUE TITLE
modules.txt is missing explicit tags

### ISSUE THREAD

**Issue by lespea** [nomad-software/vend#6]
Without these tags go 1.14 errors with `{module} is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt`

Example: https://golang.org/src/vendor/modules.txt

I'm currently getting around this by running `go mod vendor`, saving their version of modules.txt, running vend, then overriding the new modules.txt with the go mod version.  I did notice that the files are different with go mod listing more sub-paths of modules and outright excluding others.  This is for an internal project so I can't really share a working example, sorry.

**Comment by nomad-software** [comment]
Yeah, I saw this when I upgraded to v1.4. The main problem is that there isn't a published spec for the `modules.txt` file. I had a cursory glance at the requirements and I can't see a good way of getting this information.

I'm also swamped at the minute and can't give this my full attention, so any help is appreciated. I will get around to it but it could be some time and if the required dependency information is not available via `go mod` commands then it probably can't be fixed.

**Comment by lespea** [comment]
Figured we could just use go to generate it and copy what they have

**Comment by nomad-software** [comment]
Excellent idea!

Does the `CopyPkgDependencies` function require this change too?

**Comment by lespea** [comment]
Good call, fixed

**Comment by nomad-software** [comment]
Excellent, thankyou!
